# Revolutionary O(1) Fingerprint System - Application Configuration
# Patent Pending - Michael Derrick Jagneaux
# Production-ready configuration for the world's first constant-time biometric matching system

# Flask Application Settings
flask:
  secret_key: "revolutionary-o1-fingerprint-system-patent-pending-2025"
  debug: true
  host: "0.0.0.0"
  port: 5000
  threaded: true
  
# Upload Configuration
upload:
  folder: "data/uploads"
  max_file_size: 16777216  # 16MB in bytes
  allowed_extensions: ["jpg", "jpeg", "png", "tif", "tiff", "bmp"]
  thumbnail_size: [200, 200]
  enable_thumbnails: true

# Database Configuration
database:
  path: "data/database/fingerprints.db"
  enable_caching: true
  max_cache_size: 10000
  cache_ttl: 3600  # 1 hour
  backup_enabled: true
  backup_interval: 86400  # 24 hours
  optimization_enabled: true
  
# Fingerprint Processing Configuration
fingerprint_processor:
  # Image preprocessing
  image_preprocessing:
    enhance_contrast: true
    normalize_brightness: true
    denoise: true
    resize_target: [512, 512]
    
  # Characteristic extraction
  characteristic_extraction:
    enable_minutiae: true
    enable_ridge_analysis: true
    enable_pattern_classification: true
    enable_quality_assessment: true
    min_minutiae_count: 10
    
  # Pattern classification
  pattern_classification:
    supported_patterns: ["ARCH", "LOOP_LEFT", "LOOP_RIGHT", "WHORL"]
    confidence_threshold: 0.7
    
  # Quality assessment
  quality_assessment:
    levels: ["EXCELLENT", "GOOD", "FAIR", "POOR"]
    thresholds:
      excellent: 0.9
      good: 0.7
      fair: 0.5
      
  # Ridge density analysis
  ridge_density:
    levels: ["HIGH", "MEDIUM", "LOW"]
    analysis_window_size: 32
    
# O(1) Address Generation
address_generation:
  # Address format: FP.{PATTERN}.{QUALITY}_{DENSITY}.{MINUTIAE}_{SPATIAL}
  address_format: "FP.{pattern}.{quality}_{density}.{minutiae}_{spatial}"
  
  # Spatial distribution bins
  spatial_bins: ["LEFT", "CENTER", "RIGHT", "TOP", "BOTTOM"]
  
  # Minutiae count bins
  minutiae_bins:
    FEW: [10, 25]
    AVG: [26, 45] 
    MANY: [46, 100]
    
  # Address validation
  validate_addresses: true
  max_address_length: 50

# Performance Monitoring
performance_monitoring:
  enabled: true
  log_all_operations: true
  track_search_times: true
  track_processing_times: true
  performance_threshold_ms: 5.0  # Alert if operations exceed 5ms
  
  # O(1) validation settings
  o1_validation:
    coefficient_variation_threshold: 0.3  # Must be < 0.3 for O(1) proof
    confidence_level: 0.95
    min_measurements: 100
    
  # Benchmarking
  benchmarking:
    enabled: true
    database_sizes: [1000, 10000, 100000, 1000000, 10000000]
    iterations_per_size: 10
    
# Security Settings
security:
  enable_cors: true
  cors_origins: ["*"]  # In production, specify exact origins
  enable_rate_limiting: false  # Disable for demos
  max_requests_per_minute: 1000
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  log_file: "logs/o1_fingerprint_system.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5
  
  # Component-specific logging
  components:
    fingerprint_processor: "DEBUG"
    database_manager: "INFO"
    performance_monitor: "INFO"
    web_app: "INFO"

# Demo and Testing Configuration
demo:
  # Pre-populate database for demos
  enable_demo_data: true
  demo_data_size: 1000  # Number of synthetic fingerprints
  
  # Performance simulation
  simulate_traditional_search: true
  traditional_search_time_per_record: 0.03  # 0.03ms per record
  
  # Test data generation
  test_data:
    patterns: ["LOOP_RIGHT", "LOOP_LEFT", "WHORL", "ARCH"]
    qualities: ["EXCELLENT", "GOOD", "FAIR"]
    densities: ["HIGH", "MEDIUM", "LOW"]

# API Configuration
api:
  enable_swagger: true
  swagger_url: "/api/docs"
  
  # Rate limiting for API endpoints
  rate_limits:
    upload: "10 per minute"
    search: "100 per minute"
    stats: "60 per minute"
    
  # Response configuration
  responses:
    include_debug_info: true
    include_performance_metrics: true
    pretty_json: true

# Export and Reporting
export:
  enabled: true
  formats: ["json", "csv", "pdf"]
  
  # Report generation
  reports:
    include_performance_charts: true
    include_o1_proof: true
    include_patent_validation: true
    
# Development Settings (Remove in production)
development:
  auto_reload: true
  debug_toolbar: false
  profiling: false
  mock_processing: false  # Set to true to skip actual image processing for testing

# Production Settings (Override in production)
production:
  debug: false
  secret_key_from_env: true
  database_connection_pool: true
  enable_ssl: true
  
# Patent and Legal
patent:
  notice: "Patent Pending - Michael Derrick Jagneaux"
  technology_name: "Revolutionary O(1) Biometric Matching System"
  claim_validation: true
  performance_documentation: true

# System Health Monitoring
health:
  enable_health_checks: true
  check_interval: 60  # seconds
  
  checks:
    database_connectivity: true
    disk_space: true
    memory_usage: true
    performance_metrics: true
    
  thresholds:
    max_memory_usage_percent: 80
    min_disk_space_gb: 1.0
    max_response_time_ms: 10.0
